#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
This is the choice-parser Doctest documentation unit testing application.

1. The first test is a simple command line input test.

>>> from router import Router
>>> r = Router()
>>> r.start(['''This is the stem
... This is an option'''])
stats: ...
stats: 1 question found.
stats: stem is 16 bytes long, 1 option found.
This is the stem
This is an option

2. The second tests the anarchy file with the IndexParser and the JsonWriter.

>>> r.start(['-i', 'input/anarchy',
...          '-o', 'output/anarchy',
...          '-p', 'IndexParser',
...          '-w', 'JsonWriter',
...          ])
stats: ...
stats: 10 questions found.
...

3. The third tests the drivers license test with the BlockParser.

>>> r.start(['-i', 'input/drivers',
...          '-o', 'output/drivers',
...          '-p', 'BlockParser',
...          ])
stats: ...
stats: 12 questions found.
...
"""

if __name__ == '__main__':
    import doctest
    doctest.testmod(optionflags = doctest.ELLIPSIS | doctest.NORMALIZE_WHITESPACE)
