#!/usr/bin/env python
# -*- coding: utf-8 -*-

from router import Router

class ChoiceTest:
    cases = {
        'String input test': {
            'input': 'This is the stem\n\nThis is an option',
            },
        'File input test 1': {
            'file': 'anarchy',
            'parser': 'IndexParser',
            },
        'File input test 2': {
            'file': 'driver',
            'parser': 'BlockParser',
            },
        'File input test 3': {
            'file': 'reading',
            'parser': 'IndexParser',
            },
        'File input test 4': {
            'file': 'writing',
            'parser': 'IndexParser',
            },
        }

    def run(self, output=False, stats=False):
        print "Test results:\n"

        for name, case in self.cases.iteritems():
            print '====================================================='
            print name, case, '\n'
            r = Router()
            args = []

            if stats:
                args.append('-s')

            if output:
                args.append('--outputfile')
                args.append('output/%s' % case.get('file'))

            if case.get('file' ):
                args.append('--inputfile')
                args.append('input/%s' % case.get('file'))

            if case.get('parser'):
                args.append('--parser')
                args.append(case.get('parser'))

            if case.get('input'):
                args.append(case.get('input'))

            r.parse_args(args)
            r.start()
            print r.output
            del r

if __name__ == '__main__':
    output = True
    stats = True

    s = ChoiceTest()
    s.run(output, stats)
