#!/usr/bin/env python
# -*- coding: utf-8 -*-

from router import Router

class ChoiceTest:
    cases = {
        'String input test': {
            'input': 'This is the stem\n\nThis is an option',
            },
        'File input test 1': {
            'file': 'anarchy',
            'parser': 'IndexParser',
            'writer': 'JsonWriter',
            },
        'File input test 2': {
            'file': 'drivers',
            'parser': 'BlockParser',
            },
        'File input test 3': {
            'file': 'reading',
            'parser': 'IndexParser',
            },
        'File input test 4': {
            'file': 'writing',
            'parser': 'IndexParser',
            },
        'File input test 5': {
            'file': 'choices',
            'parser': 'IndexParser',
            'filters': 'QualifiedFilter',
            },
        }

    def run(self, output=False, silent=False):
        print "Test results:\n"

        for name, case in self.cases.iteritems():
            print '====================================================='
            print name, case, '\n'
            r = Router()
            args = []

            if silent:
                args.append('-s')

            if case.get('file' ):
                args.append('-i')
                args.append('input/%s' % case.get('file'))

            if output:
                args.append('-o')
                args.append('output/%s' % case.get('file'))

            if case.get('parser'):
                args.append('-p')
                args.append(case.get('parser'))

            if case.get('filters'):
                args.append('-f')
                args.append(case.get('filters'))

            if case.get('writer'):
                args.append('-w')
                args.append(case.get('writer'))

            if case.get('input'):
                args.append(case.get('input'))

            r.start(args)
            del r

if __name__ == '__main__':
    output = True
    silent = False

    s = ChoiceTest()
    s.run(output, silent)
