#!/usr/bin/env python
# -*- coding: utf-8 -*-

from router import Router

class ChoiceTest:
    cases = {
        'String input test': {
            'input': 'This is the stem\n\nThis is an option',
            },
        'File input test 1': {
            'file': 'data/anarchy',
            'parser': 'IndexParser',
            },
        'File input test 2': {
            'file': 'data/driver',
            'parser': 'BlockParser',
            },
        }
    def run(self):
        print "Test results:\n"

        for name, case in self.cases.iteritems():
            print '====================================================='
            print name, case, '\n'
            r = Router()
            args = []

            if case.get('file' ): 
                args.append('--inputfile')
                args.append(case.get('file' ))

            if case.get('parser' ): 
                args.append('--parser')
                args.append(case.get('parser' ))

            if case.get('input'): 
                args.append(case.get('input'))

            r.parse_args(args)
            r.start()
            print r.output
            del r

if __name__ == '__main__':
    s = ChoiceTest()
    s.run()
